### ISSUE TITLE
renaming columns?

### ISSUE THREAD

**Issue by slyrus** [sirherrbatka/vellum#12]
How do we rename columns? This is an important feature that we should export and document.

**Comment by sirherrbatka** [comment]
There is no way to do this right now.

**Comment by sirherrbatka** [comment]
Furthermore, I would rather suggest we make a general purpose tool that not only renames column, but also can be used to change other attributes of column. A slightly more challenging undertaking.

**Comment by sirherrbatka** [comment]
Ok, so I created alter-header branch. I envision this to work like this:

(alter-header header '((:change example-column-name (:name new-name)) (:change 1 (:name new-name-for-previously-unamed-column :predicate new-predicate)) (:new (:name a-new-column))

This function should return new instance of the header, signal condition when: changing non-existing column signature, changing the same column more then once, name duplication. Swaping names between two columns should be allowed. After finishing this we can implement ALTER-TABLE. Then we will have to rewrite (or remove) new-column function.

Wanna take a stab at it or should I handle this myself?

**Comment by slyrus** [comment]
I'm still pretty naive about the header internals. If you could point me more in the right direction of how to do this, that would be great.

**Comment by sirherrbatka** [comment]
Gladly. 

So far now, let's just focus on the header. In the module header we have class called STANDARD-HEADER has 3 slots. %column-signature-class is of no concern. %column-signatures is a vector of column-signature-objects. %column-names maps textual name of the column to the index in the %column-signatures object. Simple enough so far.

COLUMN-SIGNATURE is class that instances hold actual detailed information about the column. Columns have name (as you already know), type (for instance BIT to save memory) and predicate (function that will check if value attempted to be placed into the column is allowed, defaults to (constantly t)). Column specification contains either just a name of a column or plist mapping with initargs and values, for instance (:name "something" :type '(unsigned-byte 8) :predicate (lambda (x) (not (zerop x))).  What we need to do is to build semantics to construct new STANDARD-HEADER withe new COLUMN-SIGNATURES based on the previous, with a changes specified in the form of the list. We will call this function ALTER-HEADER and everything else I described previously. 

Makes sense?

**Comment by sirherrbatka** [comment]
I've just introduced changes to the API that will permit renaming columns via table:select function. I will add examples to readme in the near future.

**Comment by sirherrbatka** [comment]
Added example to readme. Closing this issue.

**Comment by slyrus** [comment]
I'm not a huge fan of combining select and whatever function renames columns. Perhaps there's a trivial way to do this, but when working with "real world" data I often have lots of columns and want to, for example, rename just one of them. That seems tedious with select. Am I missing something?

**Comment by sirherrbatka** [comment]
This is an unfortunate side effect. But I think that this can be solved without the introduction of separate rename-columns function.

**Comment by sirherrbatka** [comment]
Ok, I've just added alter-columns function that works almost like select 
(alter-columns table '(existing-column-name new-column-name)).

Cyrus Harmon:
> I'm not a huge fan of combining select and whatever function renames
> columns. Perhaps there's a trivial way to do this, but when working with
> "real world" data I often have lots of columns and want to, for example,
> rename just one of them. That seems tedious with select. Am I missing
> something?
