### ISSUE TITLE
convert table to list/array

### ISSUE THREAD

**Issue by slyrus** [sirherrbatka/vellum#17]
Are there built-in functions to convert a table to a list of lists, (preferably with the column names as the first list), and/or an array?

**Comment by sirherrbatka** [comment]
Reasonable request. You can do the following now (just added).
(vellum:pipeline (table) (cl-ds.alg:to-list :key (vellum.selection::row-to-list)))
By default row-to-list will extract all rows, but it accepts the same arguments as the VS function. CL-DS.ALG also contains to-vector and to-hash-table. Those are aggregation function so it works just fine with cl-ds.alg:group-by. There is also peculiar macro vellum:brr that can be used to convert some of the row to list (it has a double mode, it will yield a single value is there is one argument, and a list if there are multiple arguments). I will add row-to-vector later (or you can do it on your own if you want to).

**Comment by sirherrbatka** [comment]
Oh, and you could actually attempt using aggregate-columns but this would be a two-stage process which does not make it convinient.

**Comment by sirherrbatka** [comment]
I also added row-to-vector. I will close this now.
