### ISSUE TITLE
can't compile in ABCL

### ISSUE THREAD

**Issue by PiotrWasik** [sirherrbatka/vellum#26]
It is hitting the hard limit for number of Java opcodes per class (cl-data-structures had the same problem but you fixed it, apparently it is a kind of optimisation that makes ABCL generate a lot of similar code branches): 

(ql:quickload :vellum)
....
#<THREAD "interpreter" native {2B782B00}>: Debugger invoked on condition of type SIMPLE-ERROR
  The assertion (<= -32768 JVM::OFFSET 32767) failed.
Restarts:
  0: CONTINUE                      Retry assertion.
  1: RETRY                         Retry compiling #<ASDF/LISP-ACTION:CL-SOURCE-FILE "vellum" "column" "internal">.

ABCL 1.9.1

C:\Users\piotr>java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

Windows 10 64 bit (but it will almost certainly behave like this in any OS, any Java version)

**Comment by sirherrbatka** [comment]
Thank you for this report. I will fix this 
tomorrow because I know EXACTLY what 
is going, but I don't have working ABCL 
setup. Will you be able to test it for me, 
please?

**Comment by PiotrWasik** [comment]
sure! and thanks

**Comment by sirherrbatka** [comment]
Ok, not EXACTLY. :-) Do you know which function in that file produces the problem to be specific?

**Comment by PiotrWasik** [comment]
I will ping you on IRC, but may not be able today.

**Comment by sirherrbatka** [comment]
Sure, I may also try to set up ABCL today. I mean… other implementations are perhaps lonely on my PC :-)

**Comment by sirherrbatka** [comment]
Ok, I think I've fixed it. I tested it on my own setup but If you can confirm that it works fine, it would be nice. :-)

**Comment by PiotrWasik** [comment]
Thanks! I will definitely test it :)

**Comment by PiotrWasik** [comment]
it loads all right, but I don't know if the tests should pass. I evaluated
what you have in tests file and got assertion (NOT (ZEROP LENGTH)) failed.

**Comment by sirherrbatka** [comment]
I will check that soon. Thanks for running tests!

**Comment by sirherrbatka** [comment]
Oh boy, tests in SBCL are passing. This is gonna be fun, I already can tell.

**Comment by sirherrbatka** [comment]
Just pushed a hopeful fix for this problem. It appears to work for me at least.

**Comment by PiotrWasik** [comment]
Thanks a lot :)

**Comment by sirherrbatka** [comment]
Test first, thank me later ;-) I am having problems getting replicable results out of ABCL.

**Comment by PiotrWasik** [comment]
you will be pleased to know that they pass :)

One of the tests throws Java exception ClassCastException - Bignum cannot be cast to Fixnum, but as the test passes, it may be a part of normal execution.

**Comment by sirherrbatka** [comment]
Oh. I haven't noticed such error. Is that replicable?

PiotrWasik pisze:
> you will be pleased to know that they pass :)
> 
> One of the tests throws Java exception ClassCastException - 
Bignum cannot be
> cast to Fixnum, but as the test passes, it may be a part of normal
> execution.
-- 
Marek Kochanowicz

**Comment by sirherrbatka** [comment]
I think that I fixed those issues, but now… tests simply won't finish. This is just plain painful.

**Comment by sirherrbatka** [comment]
Right now vellum semi works on ABCL. I will work to iron out failing edge cases.

**Comment by sirherrbatka** [comment]
Ok, that was actually quite simple. It was just a matter of vellum-tests using (random most-positive-fixnum) and assuming that the value will be unique. It is not. It seems that all tests are passing now on ABCL. Enjoy!

**Comment by PiotrWasik** [comment]
Yay! Thanks (and I will thank again later when I try it)

**Comment by sirherrbatka** [comment]
Also don't forget to update cl-
ds.
