### ISSUE TITLE
why alias?

### ISSUE THREAD

**Issue by slyrus** [sirherrbatka/vellum#3]
Why are column names considered aliases? I would think each column would have a name (possibly nil). I can imagine additional ways to refer a column considered aliases, but I would have thought that each column would have a "name". Am I missing something?

**Comment by sirherrbatka** [comment]
Well, it just seemed to make sense at the time. I would not expect this to become confusing.

**Comment by sirherrbatka** [comment]
@slyrus do you think we should change this? It is trivial to do and if we want to do so, now is the time.

**Comment by slyrus** [comment]
Yes, I think the proper term is "name" and we should make there are functions for getting the names, renaming columns, etc...

**Comment by sirherrbatka** [comment]
Very well. I will handle this myself.

**Comment by sirherrbatka** [comment]
https://github.com/sirherrbatka/vellum/pull/8

**Comment by sirherrbatka** [comment]
Ok, done. It seems that I did not broke anything in the process... at least of what I know of.
