### ISSUE TITLE
PLOTLY-FORMAT-NO-NULLS arg mismatch

### ISSUE THREAD

**Issue by slyrus** [sirherrbatka/vellum#4]
With the new master code, I see the following warning which gets promoted to an error:

```
The function PLOTLY-FORMAT-NO-NULLS is called with three arguments, but wants exactly two.
```

**Comment by slyrus** [comment]
Also, this is a good example of something that shouldn't be part of the vellum "core".

**Comment by sirherrbatka** [comment]
hmmm, interesting. Will take a look at this later.

**Comment by sirherrbatka** [comment]
And yeah, probabbly separate system for this would be better, but this has fairly low priority as it does not involve any extra dependencies.
