### ISSUE TITLE
package export annoyances

### ISSUE THREAD

**Issue by slyrus** [sirherrbatka/vellum#7]
The way the export stuff is done with the rexport macro, SBCL gives a warning when the ASDF system is reloaded, which, thanks to ASDF, gets promoted to an error. While not exactly incorrect, this is a pain for interactive development. Can we reconsider this approach?

**Comment by slyrus** [comment]
Also, why are we exporting symbols from other packages?

**Comment by sirherrbatka** [comment]
Well, maybe we can just muffle those warnings?

Cyrus Harmon pisze:
> The way the export stuff is done with the rexport macro, SBCL gives a
> warning when the ASDF system is reloaded, which, thanks to ASDF, gets
> promoted to an error. While not exactly incorrect, this is a pain for
> interactive development. Can we reconsider this approach?

**Comment by sirherrbatka** [comment]
We are exporting symbols that are supposed to be the high level dictionary 
into API package for the sake of simplicity.

Cyrus Harmon pisze:
> Also, why are we exporting symbols from other packages?

**Comment by slyrus** [comment]
I get exporting our own symbols but do we really want to re-export alexandria, serapeum, etc...? Why not just have the other internal packages :use those libraries instead of reexporting them from aux-package?

**Comment by sirherrbatka** [comment]
Certainly not from alexandria or serapeum. IIRC, the only symbol outside of 
vellum that is exported is cl-ds:replica. This can be changed as well.

**Comment by sirherrbatka** [comment]
Ah, sorry i misunderstood you. :use is EVIL and out of the question. I will 
write different kind of macro, one that will expand into defpackage form. This 
will solve issue you described.

**Comment by slyrus** [comment]
Ok. I'm not sure it's EVIL, but I take your point. We could use something like https://github.com/phoe/trivial-package-local-nicknames or we can roll our own macro. I think I see what you're driving at here.

**Comment by slyrus** [comment]
I have a macro that I think does what you want. Want to see a PR?

**Comment by sirherrbatka** [comment]
@slyrus i actually just pushed my own solution. It may cause some eye bleeding though ;-)

**Comment by slyrus** [comment]
Ok, we had similar thoughts. My implementation was:
```
(cl:defmacro def-fancy-package (package &rest options)
  (let ((reexports nil))
    (dolist (option options)
      (unless (consp option)
        (error "bogus FANCY-PACKAGE option: ~S" option))
      (destructuring-bind (optname . optval)
          option
        (case optname
          (:reexport
           (push optval reexports)))))
    `(eval-when (:compile-toplevel :load-toplevel :execute)
       (defpackage ,package
         ,@(remove :reexport options :key #'car)
         ,@(loop for rexport-spec in reexports
              append
                (destructuring-bind (rpackage . rsymbols)
                    rexport-spec
                  `((:import-from ,rpackage ,@rsymbols)
                    (:export ,@rsymbols))))))))

```

**Comment by slyrus** [comment]
which allows for, e.g.:
```
(fancy-package:def-fancy-package :test-package
  (:use #:cl)
  (:reexport #:alexandria
                #:if-let
                #:when-let)
  (:reexport #:serapeum
             #:~>
             #:->)
  (:reexport #:metabang.bind
             #:bind))

```

**Comment by sirherrbatka** [comment]
Well, your version is much nicer, but the issue is that we don't really have a package suitable for it. Maybe we could submit it into serapeum? I do this reexport stuff in almost every project.

**Comment by slyrus** [comment]
Sure, but for now we could just make a vellum-fancy-package package and use it here.

**Comment by slyrus** [comment]
Do you want me to put my version in place or leave yours? I'm OK either way. Thanks!

**Comment by sirherrbatka** [comment]
I think that your version is much nicer, and I would rather use it. If you are willing to handle this, go ahead, just don't really name it vellum-fancy-package. You may add vellum.utils that will be loaded before aux-package. Normally I want to avoid writing my own utils but this seems to be the best option now. And we can add there destructuring-setf there as well :-)

**Comment by sirherrbatka** [comment]
Or, alternativly, we can just to this manually. There is a lot of symbols to consider, true, but that package does not change.

**Comment by slyrus** [comment]
Ok, just pushed fancy-package-2.
